//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 01:34:08 PM KRAT 
//


package com.tfoms.smev3.health.worth.query.request;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * <p>Java class for InsuredRenderingInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsuredRenderingInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateRenderingFrom" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DateRenderingTo" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CareRegimen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CareType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MedServicesSum" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ClinicName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RegionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuredRenderingInfoType", namespace = "http://ffoms.ru/GetInsuredRenderedMedicalServices/1.0.0", propOrder = {
    "dateRenderingFrom",
    "dateRenderingTo",
    "careRegimen",
    "careType",
    "name",
    "medServicesSum",
    "clinicName",
    "regionName"
})
public class InsuredRenderingInfoType {

    @XmlElement(name = "DateRenderingFrom", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateRenderingFrom;
    @XmlElement(name = "DateRenderingTo")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateRenderingTo;
    @XmlElement(name = "CareRegimen", required = true)
    protected String careRegimen;
    @XmlElement(name = "CareType", required = true)
    protected String careType;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "MedServicesSum", required = true)
    protected BigDecimal medServicesSum;
    @XmlElement(name = "ClinicName", required = true)
    protected String clinicName;
    @XmlElement(name = "RegionName", required = true)
    protected String regionName;

    /**
     * Gets the value of the dateRenderingFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateRenderingFrom() {
        return dateRenderingFrom;
    }

    /**
     * Sets the value of the dateRenderingFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateRenderingFrom(XMLGregorianCalendar value) {
        this.dateRenderingFrom = value;
    }

    /**
     * Gets the value of the dateRenderingTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateRenderingTo() {
        return dateRenderingTo;
    }

    /**
     * Sets the value of the dateRenderingTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateRenderingTo(XMLGregorianCalendar value) {
        this.dateRenderingTo = value;
    }

    /**
     * Gets the value of the careRegimen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareRegimen() {
        return careRegimen;
    }

    /**
     * Sets the value of the careRegimen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareRegimen(String value) {
        this.careRegimen = value;
    }

    /**
     * Gets the value of the careType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCareType() {
        return careType;
    }

    /**
     * Sets the value of the careType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCareType(String value) {
        this.careType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the medServicesSum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMedServicesSum() {
        return medServicesSum;
    }

    /**
     * Sets the value of the medServicesSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMedServicesSum(BigDecimal value) {
        this.medServicesSum = value;
    }

    /**
     * Gets the value of the clinicName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicName() {
        return clinicName;
    }

    /**
     * Sets the value of the clinicName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicName(String value) {
        this.clinicName = value;
    }

    /**
     * Gets the value of the regionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * Sets the value of the regionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionName(String value) {
        this.regionName = value;
    }

}
