//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 01:34:08 PM KRAT 
//


package com.tfoms.smev3.health.worth.query.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the health.worth.query.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InputData_QNAME = new QName("http://ffoms.ru/GetInsuredRenderedMedicalServices/1.0.0", "InputData");
    private final static QName _SovietPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "SovietPassport");
    private final static QName _InternationalPassportRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "InternationalPassportRF");
    private final static QName _OutputData_QNAME = new QName("http://ffoms.ru/GetInsuredRenderedMedicalServices/1.0.0", "OutputData");
    private final static QName _MilitaryPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "MilitaryPassport");
    private final static QName _SailorPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "SailorPassport");
    private final static QName _AttachmentRef_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "AttachmentRef");
    private final static QName _DrivingLicenseRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "DrivingLicenseRF");
    private final static QName _PassportLossCertificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "PassportLossCertificate");
    private final static QName _ForeignPassport_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "ForeignPassport");
    private final static QName _TemporaryIdentityCardRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "TemporaryIdentityCardRF");
    private final static QName _PassportRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "PassportRF");
    private final static QName _IdentityDocument_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "IdentityDocument");
    private final static QName _PrimaryIdentityDocument_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "PrimaryIdentityDocument");
    private final static QName _BirthCertificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "BirthCertificate");
    private final static QName _Form9Certificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "Form9Certificate");
    private final static QName _ResidencePermitRF_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "ResidencePermitRF");
    private final static QName _ReleaseCertificate_QNAME = new QName("urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", "ReleaseCertificate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: health.worth.query.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OutputDataType }
     * 
     */
    public OutputDataType createOutputDataType() {
        return new OutputDataType();
    }

    /**
     * Create an instance of {@link InputDataType }
     * 
     */
    public InputDataType createInputDataType() {
        return new InputDataType();
    }

    /**
     * Create an instance of {@link InsuredRenderingInfoType }
     * 
     */
    public InsuredRenderingInfoType createInsuredRenderingInfoType() {
        return new InsuredRenderingInfoType();
    }

    /**
     * Create an instance of {@link InsuredRenderingListRequestType }
     * 
     */
    public InsuredRenderingListRequestType createInsuredRenderingListRequestType() {
        return new InsuredRenderingListRequestType();
    }

    /**
     * Create an instance of {@link InsuredRenderingListType }
     * 
     */
    public InsuredRenderingListType createInsuredRenderingListType() {
        return new InsuredRenderingListType();
    }

    /**
     * Create an instance of {@link NotRestrictedDocumentType }
     * 
     */
    public NotRestrictedDocumentType createNotRestrictedDocumentType() {
        return new NotRestrictedDocumentType();
    }

    /**
     * Create an instance of {@link PassportRFType }
     * 
     */
    public PassportRFType createPassportRFType() {
        return new PassportRFType();
    }

    /**
     * Create an instance of {@link PrimaryIdentityDocumentType }
     * 
     */
    public PrimaryIdentityDocumentType createPrimaryIdentityDocumentType() {
        return new PrimaryIdentityDocumentType();
    }

    /**
     * Create an instance of {@link AnyIdentityDocumentType }
     * 
     */
    public AnyIdentityDocumentType createAnyIdentityDocumentType() {
        return new AnyIdentityDocumentType();
    }

    /**
     * Create an instance of {@link SovietPassportType }
     * 
     */
    public SovietPassportType createSovietPassportType() {
        return new SovietPassportType();
    }

    /**
     * Create an instance of {@link InternationalPassportRFType }
     * 
     */
    public InternationalPassportRFType createInternationalPassportRFType() {
        return new InternationalPassportRFType();
    }

    /**
     * Create an instance of {@link MilitaryPassportDocumentType }
     * 
     */
    public MilitaryPassportDocumentType createMilitaryPassportDocumentType() {
        return new MilitaryPassportDocumentType();
    }

    /**
     * Create an instance of {@link AttachmentRefType }
     * 
     */
    public AttachmentRefType createAttachmentRefType() {
        return new AttachmentRefType();
    }

    /**
     * Create an instance of {@link DrivingLicenseRFType }
     * 
     */
    public DrivingLicenseRFType createDrivingLicenseRFType() {
        return new DrivingLicenseRFType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ffoms.ru/GetInsuredRenderedMedicalServices/1.0.0", name = "InputData")
    public JAXBElement<InputDataType> createInputData(InputDataType value) {
        return new JAXBElement<InputDataType>(_InputData_QNAME, InputDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SovietPassportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "SovietPassport")
    public JAXBElement<SovietPassportType> createSovietPassport(SovietPassportType value) {
        return new JAXBElement<SovietPassportType>(_SovietPassport_QNAME, SovietPassportType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalPassportRFType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "InternationalPassportRF")
    public JAXBElement<InternationalPassportRFType> createInternationalPassportRF(InternationalPassportRFType value) {
        return new JAXBElement<InternationalPassportRFType>(_InternationalPassportRF_QNAME, InternationalPassportRFType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OutputDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ffoms.ru/GetInsuredRenderedMedicalServices/1.0.0", name = "OutputData")
    public JAXBElement<OutputDataType> createOutputData(OutputDataType value) {
        return new JAXBElement<OutputDataType>(_OutputData_QNAME, OutputDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MilitaryPassportDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "MilitaryPassport")
    public JAXBElement<MilitaryPassportDocumentType> createMilitaryPassport(MilitaryPassportDocumentType value) {
        return new JAXBElement<MilitaryPassportDocumentType>(_MilitaryPassport_QNAME, MilitaryPassportDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MilitaryPassportDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "SailorPassport")
    public JAXBElement<MilitaryPassportDocumentType> createSailorPassport(MilitaryPassportDocumentType value) {
        return new JAXBElement<MilitaryPassportDocumentType>(_SailorPassport_QNAME, MilitaryPassportDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "AttachmentRef")
    public JAXBElement<AttachmentRefType> createAttachmentRef(AttachmentRefType value) {
        return new JAXBElement<AttachmentRefType>(_AttachmentRef_QNAME, AttachmentRefType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DrivingLicenseRFType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "DrivingLicenseRF")
    public JAXBElement<DrivingLicenseRFType> createDrivingLicenseRF(DrivingLicenseRFType value) {
        return new JAXBElement<DrivingLicenseRFType>(_DrivingLicenseRF_QNAME, DrivingLicenseRFType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "PassportLossCertificate")
    public JAXBElement<NotRestrictedDocumentType> createPassportLossCertificate(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_PassportLossCertificate_QNAME, NotRestrictedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "ForeignPassport")
    public JAXBElement<NotRestrictedDocumentType> createForeignPassport(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_ForeignPassport_QNAME, NotRestrictedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "TemporaryIdentityCardRF")
    public JAXBElement<NotRestrictedDocumentType> createTemporaryIdentityCardRF(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_TemporaryIdentityCardRF_QNAME, NotRestrictedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PassportRFType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "PassportRF")
    public JAXBElement<PassportRFType> createPassportRF(PassportRFType value) {
        return new JAXBElement<PassportRFType>(_PassportRF_QNAME, PassportRFType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyIdentityDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "IdentityDocument")
    public JAXBElement<AnyIdentityDocumentType> createIdentityDocument(AnyIdentityDocumentType value) {
        return new JAXBElement<AnyIdentityDocumentType>(_IdentityDocument_QNAME, AnyIdentityDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimaryIdentityDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "PrimaryIdentityDocument")
    public JAXBElement<PrimaryIdentityDocumentType> createPrimaryIdentityDocument(PrimaryIdentityDocumentType value) {
        return new JAXBElement<PrimaryIdentityDocumentType>(_PrimaryIdentityDocument_QNAME, PrimaryIdentityDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SovietPassportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "BirthCertificate")
    public JAXBElement<SovietPassportType> createBirthCertificate(SovietPassportType value) {
        return new JAXBElement<SovietPassportType>(_BirthCertificate_QNAME, SovietPassportType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "Form9Certificate")
    public JAXBElement<NotRestrictedDocumentType> createForm9Certificate(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_Form9Certificate_QNAME, NotRestrictedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalPassportRFType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "ResidencePermitRF")
    public JAXBElement<InternationalPassportRFType> createResidencePermitRF(InternationalPassportRFType value) {
        return new JAXBElement<InternationalPassportRFType>(_ResidencePermitRF_QNAME, InternationalPassportRFType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.2", name = "ReleaseCertificate")
    public JAXBElement<NotRestrictedDocumentType> createReleaseCertificate(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_ReleaseCertificate_QNAME, NotRestrictedDocumentType.class, null, value);
    }

}
