//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 01:32:40 PM KRAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn://x-artefacts-smev-gov-ru/services/service-adapter/types",
									  elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,

									xmlns = {
												        @XmlNs(prefix="tns1", namespaceURI="urn://x-artefacts-smev-gov-ru/services/service-adapter/types")
												    }
										)
package com.tfoms.smev3.egr_zags.adapter.request.request;

import javax.xml.bind.annotation.XmlNs;
