//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 01:32:40 PM KRAT 
//


package com.tfoms.smev3.egr_zags.adapter.request.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryTypeCriteria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryTypeCriteria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messageTypeCriteria" type="{urn://x-artefacts-smev-gov-ru/services/service-adapter/types}TypeCriteria"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryTypeCriteria", propOrder = {
    "messageTypeCriteria"
})
public class QueryTypeCriteria {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TypeCriteria messageTypeCriteria;

    /**
     * Gets the value of the messageTypeCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCriteria }
     *     
     */
    public TypeCriteria getMessageTypeCriteria() {
        return messageTypeCriteria;
    }

    /**
     * Sets the value of the messageTypeCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCriteria }
     *     
     */
    public void setMessageTypeCriteria(TypeCriteria value) {
        this.messageTypeCriteria = value;
    }

}
